/**
 * Stamps the deployed page with the identity of the build it belongs to.
 *
 *   node scripts/stamp-version.mjs [root]   # root defaults to `web`
 *
 * GitHub Pages serves everything with a fixed `Cache-Control: max-age=600` and
 * offers no way to change it, so the browser is entitled to keep any file for
 * ten minutes and — for a page saved to a phone's home screen, which is
 * relaunched rather than reloaded — effectively forever. The page therefore
 * has to notice for itself that it has gone stale.
 *
 * That needs two facts the app cannot otherwise know:
 *
 *   `lib/build.js`   the version of the code that is *running*. It rides
 *                    inside the module graph, so a stale copy of the app
 *                    carries a stale version with it. That is the point.
 *   `version.json`   the version on the *server*, fetched `no-store`.
 *
 * A mismatch means the running code is old. `ASSETS` then lists everything
 * that has to be refetched to fix it, so the update lands as one whole build
 * rather than a mix of old and new modules.
 *
 * Both outputs are generated, never committed: a checked-in stamp is wrong the
 * moment anyone edits a file next to it, and a wrong stamp is worse than none.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Paths the stamp covers, relative to the root, sorted for a stable hash.
 *
 * @param {string} root
 * @returns {string[]}
 */
export function assetFiles(root) {
  /** @type {string[]} */
  const out = [];
  /** @param {string} dir */
  const walk = (dir) => {
    for (const entry of readdirSync(dir).sort()) {
      const path = join(dir, entry);
      const rel = relative(root, path).split(sep).join('/');
      // `data/` is excluded on purpose. The snapshot and the sidecars are
      // already fetched `no-cache`, so a data refresh reaches an open page
      // without reloading it — folding them in would only churn the version
      // every weekday and reload the app to no effect.
      if (rel === 'data' || rel === 'version.json' || rel === 'lib/build.js') continue;
      // A type declaration is deployed but never loaded, so it is neither an
      // asset to warm nor something whose contents can make a page stale.
      if (rel.endsWith('.d.ts')) continue;
      if (statSync(path).isDirectory()) walk(path);
      else out.push(rel);
    }
  };
  walk(root);
  return out;
}

/**
 * A short digest over the bytes *and* the names of every asset.
 *
 * @param {string} root
 * @param {string[]} files
 */
export function versionOf(root, files) {
  const h = createHash('sha256');
  for (const rel of files) {
    // The name is hashed alongside the bytes so that a pure rename — which
    // changes what the browser must fetch, but no file's contents — still
    // moves the version.
    h.update(rel).update('\0').update(readFileSync(join(root, rel))).update('\0');
  }
  return h.digest('hex').slice(0, 12);
}

/** @param {string} root */
export function stamp(root = 'web') {
  const files = assetFiles(root);
  const version = versionOf(root, files);
  // `index.html` is hashed but not listed: the document is refetched by the
  // reload itself, and warming it under this URL would fill a cache entry the
  // navigation does not read.
  const assets = files.filter((f) => f !== 'index.html');

  writeFileSync(
    join(root, 'lib', 'build.js'),
    `// Generated by scripts/stamp-version.mjs. Not committed; do not edit.\n` +
      `export const VERSION = ${JSON.stringify(version)};\n` +
      `export const ASSETS = ${JSON.stringify(assets, null, 2)};\n`,
  );
  writeFileSync(join(root, 'version.json'), `${JSON.stringify({ version })}\n`);
  return { version, assets };
}

// Only when run directly, so the helpers above stay importable from a test.
if (process.argv[1] && process.argv[1].endsWith('stamp-version.mjs')) {
  const { version, assets } = stamp(process.argv[2] ?? 'web');
  console.log(`stamped ${version} over ${assets.length} assets`);
}
